[package]
name = "bevy-wasm-ball-shooter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
opt-level = 'z'
lto = true

[dependencies]
bevy = "0.10.1"
bevy_prototype_debug_lines = { version = "0.10.2", features = ["3d"] }
bevy_rapier3d = "0.21.0"
fastrand = "2.0.0"
